### ISSUE TITLE
Failed create pod sandbox

### ISSUE THREAD

**Issue by ycrxun** [XiaoMi/naftis#4]
```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
``` 
```shell
$ kubectl describe pod -n naftis naftis-api-0
Name:           naftis-api-0
Namespace:      naftis
Node:           192.168.100.101/192.168.100.101
Start Time:     Thu, 25 Oct 2018 09:17:25 -0400
Labels:         app=naftis-api
                controller-revision-hash=naftis-api-5dc5f875
                release=naftis
                statefulset.kubernetes.io/pod-name=naftis-api-0
Annotations:    <none>
Status:         Running
IP:             172.20.2.37
Controlled By:  StatefulSet/naftis-api
Containers:
  naftis-api:
    Container ID:  docker://a93bc414f2c81955f0e8427e63c71b3ac691cc7a33e3a60aeaf049830fa7da4e
    Image:         docker.io/sevennt/naftis-api:latest
    Image ID:      docker-pullable://sevennt/naftis-api@sha256:92ae3a89f00e11c8806f8a6161c83f09d4724c2740c86147ed8645fe1ca68481
    Port:          50000/TCP
    Host Port:     0/TCP
    Args:
      --config=/etc/naftis/config/config.toml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 25 Oct 2018 10:37:47 -0400
      Finished:     Thu, 25 Oct 2018 10:37:48 -0400
    Ready:          False
    Restart Count:  19
    Liveness:       http-get http://:50000/api/probe/healthy delay=30s timeout=30s period=10s #success=1 #failure=3
    Readiness:      http-get http://:50000/api/probe/healthy delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /etc/naftis/config from naftis-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jl84z (ro)
  reloader:
    Container ID:  docker://6cc5d25880966837a8ffd45cc2eecc6428808cfa698a57213a02dde89514fe7d
    Image:         nghialv2607/k8s-config-reloader:v0.1.0
    Image ID:      docker-pullable://nghialv2607/k8s-config-reloader@sha256:7baea618e7558474da1b2af7493252a39bad484b89d9474acd0af96cec2ecbf4
    Port:          <none>
    Host Port:     <none>
    Args:
      --config.promviz-reload-url=http://localhost:50000/reload
      --config.promviz-config-dir=/etc/naftis
      --config.log-level=info
    State:          Running
      Started:      Thu, 25 Oct 2018 10:26:53 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 25 Oct 2018 10:11:26 -0400
      Finished:     Thu, 25 Oct 2018 10:26:52 -0400
    Ready:          True
    Restart Count:  3
    Limits:
      cpu:     50m
      memory:  64Mi
    Requests:
      cpu:        20m
      memory:     32Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jl84z (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  naftis-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      naftis-config
    Optional:  false
  default-token-jl84z:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-jl84z
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                  Age                 From                      Message
  ----     ------                  ----                ----                      -------
  Normal   Scheduled               1h                  default-scheduler         Successfully assigned naftis/naftis-api-0 to 192.168.100.101
  Normal   Pulling                 1h                  kubelet, 192.168.100.101  pulling image "docker.io/sevennt/naftis-api:latest"
  Normal   Pulled                  1h                  kubelet, 192.168.100.101  Successfully pulled image "docker.io/sevennt/naftis-api:latest"
  Normal   Pulling                 1h                  kubelet, 192.168.100.101  pulling image "nghialv2607/k8s-config-reloader:v0.1.0"
  Normal   Pulled                  1h                  kubelet, 192.168.100.101  Successfully pulled image "nghialv2607/k8s-config-reloader:v0.1.0"
  Normal   Created                 1h                  kubelet, 192.168.100.101  Created container
  Normal   Started                 1h                  kubelet, 192.168.100.101  Started container
  Normal   Pulled                  1h (x3 over 1h)     kubelet, 192.168.100.101  Container image "docker.io/sevennt/naftis-api:latest" already present on machine
  Normal   Created                 1h (x4 over 1h)     kubelet, 192.168.100.101  Created container
  Normal   Started                 1h (x4 over 1h)     kubelet, 192.168.100.101  Started container
  Warning  Unhealthy               1h                  kubelet, 192.168.100.101  Readiness probe failed: Get http://172.20.2.22:50000/api/probe/healthy: dial tcp 172.20.2.22:50000: connect: connection refused
  Warning  BackOff                 1h (x14 over 1h)    kubelet, 192.168.100.101  Back-off restarting failed container
  Warning  FailedCreatePodSandBox  43m                 kubelet, 192.168.100.101  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "413c6742cbc22c3769088b8b5235ec247df57a09b4bb9c02cd885755b18a0d77" network for pod "naftis-api-0": NetworkPlugin cni failed to set up pod "naftis-api-0_naftis" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  43m                 kubelet, 192.168.100.101  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "5c53cbd5d248fe522076382647bdb63e4660d7abecea19538b6424de4b8f5c43" network for pod "naftis-api-0": NetworkPlugin cni failed to set up pod "naftis-api-0_naftis" network: open /run/flannel/subnet.env: no such file or directory
  Normal   SandboxChanged          43m (x3 over 43m)   kubelet, 192.168.100.101  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                  43m                 kubelet, 192.168.100.101  Container image "nghialv2607/k8s-config-reloader:v0.1.0" already present on machine
  Normal   Created                 43m                 kubelet, 192.168.100.101  Created container
  Normal   Started                 43m                 kubelet, 192.168.100.101  Started container
  Normal   Pulled                  42m (x3 over 43m)   kubelet, 192.168.100.101  Container image "docker.io/sevennt/naftis-api:latest" already present on machine
  Normal   Created                 42m (x3 over 43m)   kubelet, 192.168.100.101  Created container
  Normal   Started                 42m (x3 over 43m)   kubelet, 192.168.100.101  Started container
  Warning  BackOff                 3m (x188 over 42m)  kubelet, 192.168.100.101  Back-off restarting failed container
```

**Comment by sevennt** [comment]
Would you mind paste some logs with `kubectl logs -f naftis-api-0 -n naftis naftis-api`?

**Comment by sevennt** [comment]
@ycrxun

**Comment by ycrxun** [comment]
@sevennt My pleasure.
```shell
$ kubectl logs -f naftis-api-0 -n naftis naftis-api
2018-10-26T11:32:59.556036Z     info    [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)
2018-10-26T11:32:59.561977Z     info    [GIN-debug] GET    /api/probe/healthy        --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.Healthy (4 handlers)
2018-10-26T11:32:59.562093Z     info    [GIN-debug] POST   /api/login/account        --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.LoginAccount (4 handlers)
2018-10-26T11:32:59.562120Z     info    [GIN-debug] GET    /api/login_user           --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.LoginUser (5 handlers)
2018-10-26T11:32:59.562136Z     info    [GIN-debug] GET    /api/diagnose             --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.ListStatus (5 handlers)
2018-10-26T11:32:59.562149Z     info    [GIN-debug] GET    /api/metrics              --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.ListMetrics (5 handlers)
2018-10-26T11:32:59.562169Z     info    [GIN-debug] GET    /api/d3graph/:svcname     --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.D3Graph (5 handlers)
2018-10-26T11:32:59.562206Z     info    [GIN-debug] GET    /api/services             --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.Services (5 handlers)
2018-10-26T11:32:59.562224Z     info    [GIN-debug] GET    /api/services/:uid        --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.Services (5 handlers)
2018-10-26T11:32:59.562239Z     info    [GIN-debug] GET    /api/services/:uid/pods   --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.ServicePods (5 handlers)
2018-10-26T11:32:59.562252Z     info    [GIN-debug] GET    /api/pods                 --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.Pods (5 handlers)
2018-10-26T11:32:59.562264Z     info    [GIN-debug] GET    /api/pods/:name           --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.Pods (5 handlers)
2018-10-26T11:32:59.562278Z     info    [GIN-debug] GET    /api/tasks                --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.ListTasks (5 handlers)
2018-10-26T11:32:59.562289Z     info    [GIN-debug] GET    /api/tasks/:id            --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.ListTasks (5 handlers)
2018-10-26T11:32:59.562324Z     info    [GIN-debug] POST   /api/tasks                --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.AddTasks (5 handlers)
2018-10-26T11:32:59.562340Z     info    [GIN-debug] GET    /api/tasktmpls            --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.ListTaskTmpls (5 handlers)
2018-10-26T11:32:59.562357Z     info    [GIN-debug] GET    /api/tasktmpls/:id        --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.ListTaskTmpls (5 handlers)
2018-10-26T11:32:59.562374Z     info    [GIN-debug] POST   /api/tasktmpls            --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.AddTaskTmpls (5 handlers)
2018-10-26T11:32:59.562388Z     info    [GIN-debug] PUT    /api/tasktmpls/:id        --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.UpdateTaskTmpls (5 handlers)
2018-10-26T11:32:59.562400Z     info    [GIN-debug] DELETE /api/tasktmpls/:id        --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.DeleteTaskTmpls (5 handlers)
2018-10-26T11:32:59.562413Z     info    [GIN-debug] GET    /api/tasktmpls/:id/vars   --> micode.be.xiaomi.com/info-arch/naftis/src/api/handler.ListTaskTmplVars (5 handlers)
2018-10-26T11:32:59.562463Z     info    [GIN-debug] GET    /ws                       --> micode.be.xiaomi.com/info-arch/naftis/src/api/router.Init.func1 (4 handlers)
panic: failed to connect database dial tcp: lookup naftis-mysql.naftis.svc.cluster.local on 10.68.0.2:53: no such host

goroutine 1 [running]:
micode.be.xiaomi.com/info-arch/naftis/src/api/storer/db.Init()
        /usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/src/api/storer/db/init.go:50 +0x22d
micode.be.xiaomi.com/info-arch/naftis/src/api/storer.Init()
        /usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/src/api/storer/init.go:23 +0x20
micode.be.xiaomi.com/info-arch/naftis/src/api/service.Init()
        /usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/src/api/service/init.go:23 +0x20
main.start(0x2342d00, 0xc42f572b70, 0x0, 0x1, 0x0, 0x0)
        /usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/src/api/main.go:89 +0x156
micode.be.xiaomi.com/info-arch/naftis/vendor/github.com/spf13/cobra.(*Command).execute(0x2342d00, 0xc42f572b50, 0x1, 0x1, 0x2342d00, 0xc42f572b50)
        /usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/vendor/github.com/spf13/cobra/command.go:762 +0x468
micode.be.xiaomi.com/info-arch/naftis/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2342aa0, 0x0, 0x17d8791, 0x1c)
        /usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/vendor/github.com/spf13/cobra/command.go:852 +0x30a
micode.be.xiaomi.com/info-arch/naftis/vendor/github.com/spf13/cobra.(*Command).Execute(0x2342aa0, 0xc42f5f9f78, 0xc4200a2058)
        /usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/src/api/main.go:129 +0x2d
```


```shell
$ kubectl get svc
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
hello          ClusterIP      10.68.57.113    <none>        8080/TCP         12d
istio-ui       LoadBalancer   10.68.0.96      <pending>     9100:27142/TCP   20h
kubernetes     ClusterIP      10.68.0.1       <none>        443/TCP          12d
naftis-mysql   ClusterIP      10.68.181.169   <none>        3306/TCP         22h
```

**Comment by sevennt** [comment]
@ycrxun there is something wrong happend when connecting MySQL instance in Kubernetes.
Would you mind paste Naftis pods' status with `kubectl get pods -n naftis | grep mysql`?

**Comment by sevennt** [comment]
@ycrxun check `naftis-mysql` pod's `STATUS` to ensure the pod is still `Running`.
If it's not `Running`, run `kubectl logs -f <your-naftis-mysql-pod-name> -n naftis` to search for more reasons.

**Comment by ycrxun** [comment]
@sevennt Thank you. But no logs. I need some time to find the problem by myself.

```shell
$ kubectl get pods -n naftis | grep mysql
naftis-mysql-7b458788bb-84vqh   1/1       Running            0          8m
naftis-mysql-test               0/1       Error              0          8m

$ kubectl logs -f naftis-mysql-7b458788bb-84vqh -n naftis
^C
$ kubectl logs -f naftis-mysql-test -n naftis
1..1
not ok 1 Testing MySQL Connection
# (in test file /tests/run.sh, line 2)
#   `mysql --host=naftis-mysql --port=3306 -u root -pWlRncGh3UWY5VQ==' failed
# mysql: [Warning] Using a password on the command line interface can be insecure.
# ERROR 2003 (HY000): Can't connect to MySQL server on 'naftis-mysql' (111)
```

**Comment by sevennt** [comment]
@ycrxun OK, I close the issue now, you can open it whenever you need helps.
